version: 2

sources:
    - name: staging
      database: windy-hangar-350613
      schema: committment_of_traders

      tables:
        - name: cot

models:
  - name: stg_cot
    description: >
      This models defines items submitted by different various traders to the CFTC

    columns:
      - name: report_id
        description: unique identifier of each record
    
        tests:
          - unique:
              severity: warn

          - not_null:
              severity: warn